DROP TABLE IF EXISTS bids CASCADE;

DROP TYPE IF EXISTS type_bid_state;

CREATE TYPE type_bid_state AS ENUM ('RUNNING', 'WIDTHDRAWN', 'WON', 'LOST');

CREATE TABLE bids
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    invoice_id uuid NOT NULL,
    bidder_account_id uuid NOT NULL,
    offer bigint NOT NULL,
    state type_bid_state NOT NULL DEFAULT 'RUNNING'::type_bid_state,
    CONSTRAINT bids_pkey PRIMARY KEY (id),
    CONSTRAINT bids_invoice_id_fkey FOREIGN KEY (invoice_id)
      REFERENCES invoices(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
    CONSTRAINT bids_bidder_account_id_fkey FOREIGN KEY (bidder_account_id)
      REFERENCES accounts(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

CREATE UNIQUE INDEX bids_invoice_id_bidder_account_id_state_running_unique
ON bids (invoice_id, bidder_account_id, state)
  WHERE state = 'RUNNING'::type_bid_state;

COMMENT ON TABLE bids IS
  'Bids represent Investor offers on invoices. They are the grouping abstraction for reconciling money transactions related to auctioning activity';
