DROP TABLE IF EXISTS transactions CASCADE;

CREATE TABLE transactions
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    bid_id bigint,
    credit_account_id uuid NOT NULL,
    debit_account_id uuid NOT NULL,
    amount bigint NOT NULL,
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT transactions_bid_id_fkey FOREIGN KEY (bid_id)
      REFERENCES bids(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
    CONSTRAINT transactions_credit_account_id_fkey FOREIGN KEY (credit_account_id)
      REFERENCES accounts(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
    CONSTRAINT transactions_debit_account_id_fkey FOREIGN KEY (debit_account_id)
      REFERENCES accounts(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

COMMENT ON TABLE transactions IS
  'Transactions record all tranfers of money. Only if the bid_id field is populated it means that the transaction is relative to a bid and reconciliation can be done within a bididng round.';
