DROP TABLE IF EXISTS transactions CASCADE;

CREATE TABLE transactions
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    invoice uuid,
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT transactions_invoice_fkey FOREIGN KEY (invoice)
      REFERENCES invoices(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

CREATE UNIQUE INDEX
  ON transactions (invoice, is_active)
  WHERE is_active = true;

COMMENT ON TABLE transactions
    IS 'Transactions are an accounting object needed to reconcile ledger entries';
