DROP TABLE IF EXISTS ledger;

CREATE TABLE ledger
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    transaction bigint NOT NULL,
    credit uuid NOT NULL,
    debit uuid NOT NULL,
    amount int NOT NULL,
    CONSTRAINT ledger_pkey PRIMARY KEY (id),
    CONSTRAINT ledger_transaction_fkey FOREIGN KEY (transaction)
      REFERENCES transactions(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
    CONSTRAINT ledger_credit_fkey FOREIGN KEY (credit)
      REFERENCES accounts(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
    CONSTRAINT ledger_debit_fkey FOREIGN KEY (debit)
      REFERENCES accounts(id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

COMMENT ON TABLE ledger
    IS 'Ledger records all tranfers of money,a nd matches it with a transaction for reconciliation';
