// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/arex/v1/arexApiV1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{0}
}

type Investor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance int64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Investor) Reset() {
	*x = Investor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Investor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Investor) ProtoMessage() {}

func (x *Investor) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Investor.ProtoReflect.Descriptor instead.
func (*Investor) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{1}
}

func (x *Investor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Investor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Investor) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type Issuer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance int64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Issuer) Reset() {
	*x = Issuer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Issuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issuer) ProtoMessage() {}

func (x *Issuer) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issuer.ProtoReflect.Descriptor instead.
func (*Issuer) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{2}
}

func (x *Issuer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Issuer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Issuer) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type Invoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IssuerAccountId string `protobuf:"bytes,2,opt,name=issuer_account_id,json=issuerAccountId,proto3" json:"issuer_account_id,omitempty"`
	Reference       string `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Denom           string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount          int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Asking          int64  `protobuf:"varint,6,opt,name=asking,proto3" json:"asking,omitempty"`
	State           string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{3}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetIssuerAccountId() string {
	if x != nil {
		return x.IssuerAccountId
	}
	return ""
}

func (x *Invoice) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Invoice) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Invoice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetAsking() int64 {
	if x != nil {
		return x.Asking
	}
	return 0
}

func (x *Invoice) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceId       string `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	BidderAccountId string `protobuf:"bytes,3,opt,name=bidder_account_id,json=bidderAccountId,proto3" json:"bidder_account_id,omitempty"`
	Offer           int64  `protobuf:"varint,4,opt,name=offer,proto3" json:"offer,omitempty"`
	State           string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{4}
}

func (x *Bid) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bid) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Bid) GetBidderAccountId() string {
	if x != nil {
		return x.BidderAccountId
	}
	return ""
}

func (x *Bid) GetOffer() int64 {
	if x != nil {
		return x.Offer
	}
	return 0
}

func (x *Bid) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetAllInvestorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Investor `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllInvestorsResponse) Reset() {
	*x = GetAllInvestorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInvestorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvestorsResponse) ProtoMessage() {}

func (x *GetAllInvestorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvestorsResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvestorsResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllInvestorsResponse) GetData() []*Investor {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllIssuersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Issuer `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllIssuersResponse) Reset() {
	*x = GetAllIssuersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllIssuersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIssuersResponse) ProtoMessage() {}

func (x *GetAllIssuersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIssuersResponse.ProtoReflect.Descriptor instead.
func (*GetAllIssuersResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllIssuersResponse) GetData() []*Issuer {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllBidsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Bid `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllBidsResponse) Reset() {
	*x = GetAllBidsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBidsResponse) ProtoMessage() {}

func (x *GetAllBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBidsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBidsResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllBidsResponse) GetData() []*Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBidByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidId int64 `protobuf:"varint,1,opt,name=bidId,proto3" json:"bidId,omitempty"`
}

func (x *GetBidByIdRequest) Reset() {
	*x = GetBidByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidByIdRequest) ProtoMessage() {}

func (x *GetBidByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBidByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{8}
}

func (x *GetBidByIdRequest) GetBidId() int64 {
	if x != nil {
		return x.BidId
	}
	return 0
}

type GetBidByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Bid `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBidByIdResponse) Reset() {
	*x = GetBidByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidByIdResponse) ProtoMessage() {}

func (x *GetBidByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBidByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{9}
}

func (x *GetBidByIdResponse) GetData() *Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBidsByInvoiceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId string `protobuf:"bytes,1,opt,name=InvoiceId,proto3" json:"InvoiceId,omitempty"`
}

func (x *GetBidsByInvoiceIdRequest) Reset() {
	*x = GetBidsByInvoiceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidsByInvoiceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByInvoiceIdRequest) ProtoMessage() {}

func (x *GetBidsByInvoiceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByInvoiceIdRequest.ProtoReflect.Descriptor instead.
func (*GetBidsByInvoiceIdRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{10}
}

func (x *GetBidsByInvoiceIdRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type GetBidsByInvoiceIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Bid `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBidsByInvoiceIdResponse) Reset() {
	*x = GetBidsByInvoiceIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidsByInvoiceIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByInvoiceIdResponse) ProtoMessage() {}

func (x *GetBidsByInvoiceIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByInvoiceIdResponse.ProtoReflect.Descriptor instead.
func (*GetBidsByInvoiceIdResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{11}
}

func (x *GetBidsByInvoiceIdResponse) GetData() []*Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBidsByInvestorIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestorId string `protobuf:"bytes,1,opt,name=InvestorId,proto3" json:"InvestorId,omitempty"`
}

func (x *GetBidsByInvestorIdRequest) Reset() {
	*x = GetBidsByInvestorIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidsByInvestorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByInvestorIdRequest) ProtoMessage() {}

func (x *GetBidsByInvestorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByInvestorIdRequest.ProtoReflect.Descriptor instead.
func (*GetBidsByInvestorIdRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{12}
}

func (x *GetBidsByInvestorIdRequest) GetInvestorId() string {
	if x != nil {
		return x.InvestorId
	}
	return ""
}

type GetBidsByInvestorIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Bid `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBidsByInvestorIdResponse) Reset() {
	*x = GetBidsByInvestorIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBidsByInvestorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByInvestorIdResponse) ProtoMessage() {}

func (x *GetBidsByInvestorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByInvestorIdResponse.ProtoReflect.Descriptor instead.
func (*GetBidsByInvestorIdResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{13}
}

func (x *GetBidsByInvestorIdResponse) GetData() []*Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId       string `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	BidderAccountId string `protobuf:"bytes,2,opt,name=bidder_account_id,json=bidderAccountId,proto3" json:"bidder_account_id,omitempty"`
	Offer           int64  `protobuf:"varint,3,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *NewBidRequest) Reset() {
	*x = NewBidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBidRequest) ProtoMessage() {}

func (x *NewBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBidRequest.ProtoReflect.Descriptor instead.
func (*NewBidRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{14}
}

func (x *NewBidRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *NewBidRequest) GetBidderAccountId() string {
	if x != nil {
		return x.BidderAccountId
	}
	return ""
}

func (x *NewBidRequest) GetOffer() int64 {
	if x != nil {
		return x.Offer
	}
	return 0
}

type NewBidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Bid `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NewBidResponse) Reset() {
	*x = NewBidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBidResponse) ProtoMessage() {}

func (x *NewBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBidResponse.ProtoReflect.Descriptor instead.
func (*NewBidResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{15}
}

func (x *NewBidResponse) GetData() *Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFulfillingBidsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId string `protobuf:"bytes,1,opt,name=InvoiceId,proto3" json:"InvoiceId,omitempty"`
}

func (x *GetFulfillingBidsRequest) Reset() {
	*x = GetFulfillingBidsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFulfillingBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulfillingBidsRequest) ProtoMessage() {}

func (x *GetFulfillingBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulfillingBidsRequest.ProtoReflect.Descriptor instead.
func (*GetFulfillingBidsRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{16}
}

func (x *GetFulfillingBidsRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type GetFulfillingBidsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Bid `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFulfillingBidsResponse) Reset() {
	*x = GetFulfillingBidsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFulfillingBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulfillingBidsResponse) ProtoMessage() {}

func (x *GetFulfillingBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulfillingBidsResponse.ProtoReflect.Descriptor instead.
func (*GetFulfillingBidsResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{17}
}

func (x *GetFulfillingBidsResponse) GetData() []*Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdjudicateBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidId int64 `protobuf:"varint,1,opt,name=bidId,proto3" json:"bidId,omitempty"`
}

func (x *AdjudicateBidRequest) Reset() {
	*x = AdjudicateBidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjudicateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjudicateBidRequest) ProtoMessage() {}

func (x *AdjudicateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjudicateBidRequest.ProtoReflect.Descriptor instead.
func (*AdjudicateBidRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{18}
}

func (x *AdjudicateBidRequest) GetBidId() int64 {
	if x != nil {
		return x.BidId
	}
	return 0
}

type AdjudicateBidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AdjudicateBidResponse) Reset() {
	*x = AdjudicateBidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjudicateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjudicateBidResponse) ProtoMessage() {}

func (x *AdjudicateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjudicateBidResponse.ProtoReflect.Descriptor instead.
func (*AdjudicateBidResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{19}
}

func (x *AdjudicateBidResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AllRunningBidsToLostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId string `protobuf:"bytes,1,opt,name=InvoiceId,proto3" json:"InvoiceId,omitempty"`
}

func (x *AllRunningBidsToLostRequest) Reset() {
	*x = AllRunningBidsToLostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllRunningBidsToLostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRunningBidsToLostRequest) ProtoMessage() {}

func (x *AllRunningBidsToLostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRunningBidsToLostRequest.ProtoReflect.Descriptor instead.
func (*AllRunningBidsToLostRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{20}
}

func (x *AllRunningBidsToLostRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type AllRunningBidsToLostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Bid `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AllRunningBidsToLostResponse) Reset() {
	*x = AllRunningBidsToLostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllRunningBidsToLostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRunningBidsToLostResponse) ProtoMessage() {}

func (x *AllRunningBidsToLostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRunningBidsToLostResponse.ProtoReflect.Descriptor instead.
func (*AllRunningBidsToLostResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{21}
}

func (x *AllRunningBidsToLostResponse) GetData() []*Bid {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllInvoicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Invoice `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllInvoicesResponse) GetData() []*Invoice {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetInvoiceByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId string `protobuf:"bytes,1,opt,name=invoiceId,proto3" json:"invoiceId,omitempty"`
}

func (x *GetInvoiceByIdRequest) Reset() {
	*x = GetInvoiceByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInvoiceByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceByIdRequest) ProtoMessage() {}

func (x *GetInvoiceByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceByIdRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{23}
}

func (x *GetInvoiceByIdRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type GetInvoiceByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Invoice `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetInvoiceByIdResponse) Reset() {
	*x = GetInvoiceByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInvoiceByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceByIdResponse) ProtoMessage() {}

func (x *GetInvoiceByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceByIdResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{24}
}

func (x *GetInvoiceByIdResponse) GetData() *Invoice {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewInvoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuerAccountId string `protobuf:"bytes,1,opt,name=issuer_account_id,json=issuerAccountId,proto3" json:"issuer_account_id,omitempty"`
	Reference       string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Denom           string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount          int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Asking          int64  `protobuf:"varint,5,opt,name=asking,proto3" json:"asking,omitempty"`
}

func (x *NewInvoiceRequest) Reset() {
	*x = NewInvoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInvoiceRequest) ProtoMessage() {}

func (x *NewInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInvoiceRequest.ProtoReflect.Descriptor instead.
func (*NewInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{25}
}

func (x *NewInvoiceRequest) GetIssuerAccountId() string {
	if x != nil {
		return x.IssuerAccountId
	}
	return ""
}

func (x *NewInvoiceRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *NewInvoiceRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *NewInvoiceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NewInvoiceRequest) GetAsking() int64 {
	if x != nil {
		return x.Asking
	}
	return 0
}

type NewInvoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Invoice `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NewInvoiceResponse) Reset() {
	*x = NewInvoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInvoiceResponse) ProtoMessage() {}

func (x *NewInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_arex_v1_arexApiV1_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInvoiceResponse.ProtoReflect.Descriptor instead.
func (*NewInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_api_arex_v1_arexApiV1_proto_rawDescGZIP(), []int{26}
}

func (x *NewInvoiceResponse) GetData() *Invoice {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_arex_v1_arexApiV1_proto protoreflect.FileDescriptor

var file_api_arex_v1_arexApiV1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72,
	0x65, 0x78, 0x41, 0x70, 0x69, 0x56, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x48, 0x0a, 0x08, 0x49, 0x6e,
	0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x22, 0x46, 0x0a, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0xbf, 0x01, 0x0a,
	0x07, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x8c,
	0x01, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3b, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x76, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x69, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x69, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x69, 0x64, 0x49,
	0x64, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42,
	0x79, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x39, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x69, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e,
	0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x42, 0x69, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x42, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x69, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x14, 0x41, 0x64, 0x6a,
	0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x62, 0x69, 0x64, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x41, 0x64, 0x6a, 0x75, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x1b, 0x41, 0x6c, 0x6c, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x54, 0x6f, 0x4c, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1c, 0x41, 0x6c, 0x6c, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x54, 0x6f, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x39, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xa3, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x73, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x35, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x4c, 0x0a, 0x0f,
	0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x73, 0x12, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x46, 0x0a, 0x0d, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x73, 0x12, 0x09, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xcb, 0x04, 0x0a, 0x0a, 0x42, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x69, 0x64, 0x73, 0x12,
	0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69,
	0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64,
	0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42,
	0x79, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x64, 0x73, 0x42, 0x79, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06,
	0x4e, 0x65, 0x77, 0x42, 0x69, 0x64, 0x12, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x42,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x65, 0x77, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x42, 0x69,
	0x64, 0x73, 0x12, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0d, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x69, 0x64,
	0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x73, 0x54, 0x6f, 0x4c, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64,
	0x73, 0x54, 0x6f, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69,
	0x64, 0x73, 0x54, 0x6f, 0x4c, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xcf, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x61, 0x72, 0x63, 0x6f, 0x73, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x61, 0x73, 0x74, 0x61,
	0x73, 0x69, 0x2f, 0x61, 0x72, 0x65, 0x78, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_arex_v1_arexApiV1_proto_rawDescOnce sync.Once
	file_api_arex_v1_arexApiV1_proto_rawDescData = file_api_arex_v1_arexApiV1_proto_rawDesc
)

func file_api_arex_v1_arexApiV1_proto_rawDescGZIP() []byte {
	file_api_arex_v1_arexApiV1_proto_rawDescOnce.Do(func() {
		file_api_arex_v1_arexApiV1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_arex_v1_arexApiV1_proto_rawDescData)
	})
	return file_api_arex_v1_arexApiV1_proto_rawDescData
}

var file_api_arex_v1_arexApiV1_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_arex_v1_arexApiV1_proto_goTypes = []interface{}{
	(*Empty)(nil),                        // 0: v1.Empty
	(*Investor)(nil),                     // 1: v1.Investor
	(*Issuer)(nil),                       // 2: v1.Issuer
	(*Invoice)(nil),                      // 3: v1.Invoice
	(*Bid)(nil),                          // 4: v1.Bid
	(*GetAllInvestorsResponse)(nil),      // 5: v1.GetAllInvestorsResponse
	(*GetAllIssuersResponse)(nil),        // 6: v1.GetAllIssuersResponse
	(*GetAllBidsResponse)(nil),           // 7: v1.GetAllBidsResponse
	(*GetBidByIdRequest)(nil),            // 8: v1.GetBidByIdRequest
	(*GetBidByIdResponse)(nil),           // 9: v1.GetBidByIdResponse
	(*GetBidsByInvoiceIdRequest)(nil),    // 10: v1.GetBidsByInvoiceIdRequest
	(*GetBidsByInvoiceIdResponse)(nil),   // 11: v1.GetBidsByInvoiceIdResponse
	(*GetBidsByInvestorIdRequest)(nil),   // 12: v1.GetBidsByInvestorIdRequest
	(*GetBidsByInvestorIdResponse)(nil),  // 13: v1.GetBidsByInvestorIdResponse
	(*NewBidRequest)(nil),                // 14: v1.NewBidRequest
	(*NewBidResponse)(nil),               // 15: v1.NewBidResponse
	(*GetFulfillingBidsRequest)(nil),     // 16: v1.GetFulfillingBidsRequest
	(*GetFulfillingBidsResponse)(nil),    // 17: v1.GetFulfillingBidsResponse
	(*AdjudicateBidRequest)(nil),         // 18: v1.AdjudicateBidRequest
	(*AdjudicateBidResponse)(nil),        // 19: v1.AdjudicateBidResponse
	(*AllRunningBidsToLostRequest)(nil),  // 20: v1.AllRunningBidsToLostRequest
	(*AllRunningBidsToLostResponse)(nil), // 21: v1.AllRunningBidsToLostResponse
	(*GetAllInvoicesResponse)(nil),       // 22: v1.GetAllInvoicesResponse
	(*GetInvoiceByIdRequest)(nil),        // 23: v1.GetInvoiceByIdRequest
	(*GetInvoiceByIdResponse)(nil),       // 24: v1.GetInvoiceByIdResponse
	(*NewInvoiceRequest)(nil),            // 25: v1.NewInvoiceRequest
	(*NewInvoiceResponse)(nil),           // 26: v1.NewInvoiceResponse
}
var file_api_arex_v1_arexApiV1_proto_depIdxs = []int32{
	1,  // 0: v1.GetAllInvestorsResponse.data:type_name -> v1.Investor
	2,  // 1: v1.GetAllIssuersResponse.data:type_name -> v1.Issuer
	4,  // 2: v1.GetAllBidsResponse.data:type_name -> v1.Bid
	4,  // 3: v1.GetBidByIdResponse.data:type_name -> v1.Bid
	4,  // 4: v1.GetBidsByInvoiceIdResponse.data:type_name -> v1.Bid
	4,  // 5: v1.GetBidsByInvestorIdResponse.data:type_name -> v1.Bid
	4,  // 6: v1.NewBidResponse.data:type_name -> v1.Bid
	4,  // 7: v1.GetFulfillingBidsResponse.data:type_name -> v1.Bid
	4,  // 8: v1.AllRunningBidsToLostResponse.data:type_name -> v1.Bid
	3,  // 9: v1.GetAllInvoicesResponse.data:type_name -> v1.Invoice
	3,  // 10: v1.GetInvoiceByIdResponse.data:type_name -> v1.Invoice
	3,  // 11: v1.NewInvoiceResponse.data:type_name -> v1.Invoice
	0,  // 12: v1.InvestorService.GetAllInvestors:input_type -> v1.Empty
	0,  // 13: v1.IssuerService.GetAllIssuers:input_type -> v1.Empty
	0,  // 14: v1.BidService.GetAllBids:input_type -> v1.Empty
	8,  // 15: v1.BidService.GetBidById:input_type -> v1.GetBidByIdRequest
	10, // 16: v1.BidService.GetBidsByInvoiceId:input_type -> v1.GetBidsByInvoiceIdRequest
	12, // 17: v1.BidService.GetBidsByInvestorId:input_type -> v1.GetBidsByInvestorIdRequest
	14, // 18: v1.BidService.NewBid:input_type -> v1.NewBidRequest
	16, // 19: v1.BidService.GetFulfillingBids:input_type -> v1.GetFulfillingBidsRequest
	18, // 20: v1.BidService.AdjudicateBid:input_type -> v1.AdjudicateBidRequest
	20, // 21: v1.BidService.AllRunningBidsToLost:input_type -> v1.AllRunningBidsToLostRequest
	0,  // 22: v1.InvoiceService.GetAllInvoices:input_type -> v1.Empty
	23, // 23: v1.InvoiceService.GetInvoiceById:input_type -> v1.GetInvoiceByIdRequest
	25, // 24: v1.InvoiceService.NewInvoice:input_type -> v1.NewInvoiceRequest
	5,  // 25: v1.InvestorService.GetAllInvestors:output_type -> v1.GetAllInvestorsResponse
	6,  // 26: v1.IssuerService.GetAllIssuers:output_type -> v1.GetAllIssuersResponse
	7,  // 27: v1.BidService.GetAllBids:output_type -> v1.GetAllBidsResponse
	9,  // 28: v1.BidService.GetBidById:output_type -> v1.GetBidByIdResponse
	11, // 29: v1.BidService.GetBidsByInvoiceId:output_type -> v1.GetBidsByInvoiceIdResponse
	13, // 30: v1.BidService.GetBidsByInvestorId:output_type -> v1.GetBidsByInvestorIdResponse
	15, // 31: v1.BidService.NewBid:output_type -> v1.NewBidResponse
	17, // 32: v1.BidService.GetFulfillingBids:output_type -> v1.GetFulfillingBidsResponse
	19, // 33: v1.BidService.AdjudicateBid:output_type -> v1.AdjudicateBidResponse
	21, // 34: v1.BidService.AllRunningBidsToLost:output_type -> v1.AllRunningBidsToLostResponse
	22, // 35: v1.InvoiceService.GetAllInvoices:output_type -> v1.GetAllInvoicesResponse
	24, // 36: v1.InvoiceService.GetInvoiceById:output_type -> v1.GetInvoiceByIdResponse
	26, // 37: v1.InvoiceService.NewInvoice:output_type -> v1.NewInvoiceResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_arex_v1_arexApiV1_proto_init() }
func file_api_arex_v1_arexApiV1_proto_init() {
	if File_api_arex_v1_arexApiV1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_arex_v1_arexApiV1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Investor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Issuer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInvestorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllIssuersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBidsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidsByInvoiceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidsByInvoiceIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidsByInvestorIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBidsByInvestorIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFulfillingBidsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFulfillingBidsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjudicateBidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjudicateBidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllRunningBidsToLostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllRunningBidsToLostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInvoicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInvoiceByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInvoiceByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewInvoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_arex_v1_arexApiV1_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewInvoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_arex_v1_arexApiV1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_arex_v1_arexApiV1_proto_goTypes,
		DependencyIndexes: file_api_arex_v1_arexApiV1_proto_depIdxs,
		MessageInfos:      file_api_arex_v1_arexApiV1_proto_msgTypes,
	}.Build()
	File_api_arex_v1_arexApiV1_proto = out.File
	file_api_arex_v1_arexApiV1_proto_rawDesc = nil
	file_api_arex_v1_arexApiV1_proto_goTypes = nil
	file_api_arex_v1_arexApiV1_proto_depIdxs = nil
}
