// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/arex/v1/arexApiV1.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InvestorServiceClient is the client API for InvestorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvestorServiceClient interface {
	GetAllInvestors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllInvestorsResponse, error)
}

type investorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvestorServiceClient(cc grpc.ClientConnInterface) InvestorServiceClient {
	return &investorServiceClient{cc}
}

func (c *investorServiceClient) GetAllInvestors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllInvestorsResponse, error) {
	out := new(GetAllInvestorsResponse)
	err := c.cc.Invoke(ctx, "/v1.InvestorService/GetAllInvestors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvestorServiceServer is the server API for InvestorService service.
// All implementations must embed UnimplementedInvestorServiceServer
// for forward compatibility
type InvestorServiceServer interface {
	GetAllInvestors(context.Context, *Empty) (*GetAllInvestorsResponse, error)
	mustEmbedUnimplementedInvestorServiceServer()
}

// UnimplementedInvestorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInvestorServiceServer struct {
}

func (UnimplementedInvestorServiceServer) GetAllInvestors(context.Context, *Empty) (*GetAllInvestorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInvestors not implemented")
}
func (UnimplementedInvestorServiceServer) mustEmbedUnimplementedInvestorServiceServer() {}

// UnsafeInvestorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvestorServiceServer will
// result in compilation errors.
type UnsafeInvestorServiceServer interface {
	mustEmbedUnimplementedInvestorServiceServer()
}

func RegisterInvestorServiceServer(s grpc.ServiceRegistrar, srv InvestorServiceServer) {
	s.RegisterService(&InvestorService_ServiceDesc, srv)
}

func _InvestorService_GetAllInvestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestorServiceServer).GetAllInvestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InvestorService/GetAllInvestors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestorServiceServer).GetAllInvestors(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InvestorService_ServiceDesc is the grpc.ServiceDesc for InvestorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvestorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InvestorService",
	HandlerType: (*InvestorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllInvestors",
			Handler:    _InvestorService_GetAllInvestors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/arex/v1/arexApiV1.proto",
}

// IssuerServiceClient is the client API for IssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IssuerServiceClient interface {
	GetAllIssuers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllIssuersResponse, error)
}

type issuerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssuerServiceClient(cc grpc.ClientConnInterface) IssuerServiceClient {
	return &issuerServiceClient{cc}
}

func (c *issuerServiceClient) GetAllIssuers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllIssuersResponse, error) {
	out := new(GetAllIssuersResponse)
	err := c.cc.Invoke(ctx, "/v1.IssuerService/GetAllIssuers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServiceServer is the server API for IssuerService service.
// All implementations must embed UnimplementedIssuerServiceServer
// for forward compatibility
type IssuerServiceServer interface {
	GetAllIssuers(context.Context, *Empty) (*GetAllIssuersResponse, error)
	mustEmbedUnimplementedIssuerServiceServer()
}

// UnimplementedIssuerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIssuerServiceServer struct {
}

func (UnimplementedIssuerServiceServer) GetAllIssuers(context.Context, *Empty) (*GetAllIssuersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllIssuers not implemented")
}
func (UnimplementedIssuerServiceServer) mustEmbedUnimplementedIssuerServiceServer() {}

// UnsafeIssuerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssuerServiceServer will
// result in compilation errors.
type UnsafeIssuerServiceServer interface {
	mustEmbedUnimplementedIssuerServiceServer()
}

func RegisterIssuerServiceServer(s grpc.ServiceRegistrar, srv IssuerServiceServer) {
	s.RegisterService(&IssuerService_ServiceDesc, srv)
}

func _IssuerService_GetAllIssuers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).GetAllIssuers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.IssuerService/GetAllIssuers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).GetAllIssuers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IssuerService_ServiceDesc is the grpc.ServiceDesc for IssuerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssuerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IssuerService",
	HandlerType: (*IssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllIssuers",
			Handler:    _IssuerService_GetAllIssuers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/arex/v1/arexApiV1.proto",
}

// InvoiceServiceClient is the client API for InvoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoiceServiceClient interface {
	GetAllInvoices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllInvoicesResponse, error)
	NewInvoice(ctx context.Context, in *NewInvoiceRequest, opts ...grpc.CallOption) (*NewInvoiceResponse, error)
}

type invoiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoiceServiceClient(cc grpc.ClientConnInterface) InvoiceServiceClient {
	return &invoiceServiceClient{cc}
}

func (c *invoiceServiceClient) GetAllInvoices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllInvoicesResponse, error) {
	out := new(GetAllInvoicesResponse)
	err := c.cc.Invoke(ctx, "/v1.InvoiceService/GetAllInvoices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) NewInvoice(ctx context.Context, in *NewInvoiceRequest, opts ...grpc.CallOption) (*NewInvoiceResponse, error) {
	out := new(NewInvoiceResponse)
	err := c.cc.Invoke(ctx, "/v1.InvoiceService/NewInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceServiceServer is the server API for InvoiceService service.
// All implementations must embed UnimplementedInvoiceServiceServer
// for forward compatibility
type InvoiceServiceServer interface {
	GetAllInvoices(context.Context, *Empty) (*GetAllInvoicesResponse, error)
	NewInvoice(context.Context, *NewInvoiceRequest) (*NewInvoiceResponse, error)
	mustEmbedUnimplementedInvoiceServiceServer()
}

// UnimplementedInvoiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInvoiceServiceServer struct {
}

func (UnimplementedInvoiceServiceServer) GetAllInvoices(context.Context, *Empty) (*GetAllInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInvoices not implemented")
}
func (UnimplementedInvoiceServiceServer) NewInvoice(context.Context, *NewInvoiceRequest) (*NewInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewInvoice not implemented")
}
func (UnimplementedInvoiceServiceServer) mustEmbedUnimplementedInvoiceServiceServer() {}

// UnsafeInvoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoiceServiceServer will
// result in compilation errors.
type UnsafeInvoiceServiceServer interface {
	mustEmbedUnimplementedInvoiceServiceServer()
}

func RegisterInvoiceServiceServer(s grpc.ServiceRegistrar, srv InvoiceServiceServer) {
	s.RegisterService(&InvoiceService_ServiceDesc, srv)
}

func _InvoiceService_GetAllInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).GetAllInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InvoiceService/GetAllInvoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).GetAllInvoices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_NewInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).NewInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InvoiceService/NewInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).NewInvoice(ctx, req.(*NewInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoiceService_ServiceDesc is the grpc.ServiceDesc for InvoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InvoiceService",
	HandlerType: (*InvoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllInvoices",
			Handler:    _InvoiceService_GetAllInvoices_Handler,
		},
		{
			MethodName: "NewInvoice",
			Handler:    _InvoiceService_NewInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/arex/v1/arexApiV1.proto",
}
